In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()
x = iris.data
y = iris.target

In [3]:
print(x.dtype)
print(y.dtype)
print(x.shape)
print(y.shape)

float64
int32
(150, 4)
(150,)


In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [7]:
x_train_tensor = torch.tensor(x_train, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train, dtype = torch.float32).long()

x_test_tensor = torch.tensor(x_test, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.float32).long()

In [8]:
x_train_tensor

tensor([[6.2000, 2.2000, 4.5000, 1.5000],
        [6.4000, 3.2000, 4.5000, 1.5000],
        [5.9000, 3.2000, 4.8000, 1.8000],
        [6.4000, 2.8000, 5.6000, 2.1000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.2000, 3.5000, 1.5000, 0.2000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [4.4000, 3.2000, 1.3000, 0.2000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [6.1000, 2.6000, 5.6000, 1.4000],
        [7.6000, 3.0000, 6.6000, 2.1000],
        [5.5000, 2.4000, 3.8000, 1.1000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [4.8000, 3.0000, 1.4000, 0.3000],
        [6.3000, 3.3000, 6.0000, 2.5000],
        [6.6000, 2.9000, 4.6000, 1.3000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.8000, 4.0000, 1.2000, 0.2000],
        [5.3000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.1000, 1.6000, 0.2000],
        [5.7000, 2.6000, 3.5000, 1

In [9]:
y_train_tensor

tensor([1, 1, 1, 2, 1, 0, 2, 2, 0, 1, 0, 2, 2, 2, 1, 1, 0, 2, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 2, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
        2, 1, 0, 2, 0, 1, 1, 0, 0, 0, 1, 2, 1, 1, 2, 1, 1, 2, 2, 0, 0, 1, 2, 1,
        1, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 0, 2, 0,
        1, 1, 2, 0, 2, 1, 1, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 2, 1])

In [10]:
from torch.utils.data import DataLoader, TensorDataset

train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size = 16, shuffle = True)

test_dataset = TensorDataset(x_test_tensor, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size = 16, shuffle = True)

In [11]:
x_in, y_out = next(iter(train_loader))

In [12]:
print(x_in.shape)
print(y_out.shape)

print(x_in.dtype)
print(y_out.dtype)

torch.Size([16, 4])
torch.Size([16])
torch.float32
torch.int64


In [13]:
import torch.nn.functional as F

class Mymodel(nn.Module):
    def __init__(self):
        super(Mymodel, self).__init__()
        self.fc1 = nn.Linear(4, 100)     #input : 4 / output : 100
        self.fc2 = nn.Linear(100, 3)     #input : 100 / output : 3
                                         #self.act = nn.Sigmoid()

    def forward(self, x):
        x = F.sigmoid(self.fc1(x))       #self.act(self.fc1(x))
        x = self.fc2(x)
        return x



In [14]:
model = Mymodel()
print(model)

Mymodel(
  (fc1): Linear(in_features=4, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=3, bias=True)
)


In [15]:
"""
model = Mymodel()

from torchsummary import summary
summary(model, (1, 4), device = 'cpu')
"""

"\nmodel = Mymodel()\n\nfrom torchsummary import summary\nsummary(model, (1, 4), device = 'cpu')\n"

In [16]:
criterion = nn.CrossEntropyLoss()                   #include softmax func.
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [18]:
num_epochs = 3000

for epoch in range(num_epochs):
    for x_batch, y_batch in train_loader:
        outputs = model(x_batch)

        optimizer.zero_grad()
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()

    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 100, Loss: 0.09345749020576477
Epoch 200, Loss: 0.022276252508163452
Epoch 300, Loss: 0.018172958865761757
Epoch 400, Loss: 0.024345964193344116
Epoch 500, Loss: 0.031180521473288536
Epoch 600, Loss: 0.012332805432379246
Epoch 700, Loss: 0.07946787029504776
Epoch 800, Loss: 0.04246392473578453
Epoch 900, Loss: 0.03475753217935562
Epoch 1000, Loss: 0.05366813763976097
Epoch 1100, Loss: 0.015500499866902828
Epoch 1200, Loss: 0.008595729246735573
Epoch 1300, Loss: 0.009687099605798721
Epoch 1400, Loss: 0.058610595762729645
Epoch 1500, Loss: 0.06263292580842972
Epoch 1600, Loss: 0.09624965488910675
Epoch 1700, Loss: 0.059582747519016266
Epoch 1800, Loss: 0.08920714259147644
Epoch 1900, Loss: 0.01186981052160263
Epoch 2000, Loss: 0.010913752019405365
Epoch 2100, Loss: 0.09854751825332642
Epoch 2200, Loss: 0.025925204157829285
Epoch 2300, Loss: 0.092097707092762
Epoch 2400, Loss: 0.03582928329706192
Epoch 2500, Loss: 0.08346422761678696
Epoch 2600, Loss: 0.04886361584067345
Epoch 2700,

In [19]:
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for x_batch, y_batch in test_loader:
        outputs = model(x_batch)
        _, predicted = torch.max(outputs.data, 1)
        total += y_batch.size(0)
        correct += (predicted == y_batch).sum().item()

print(f'Accuracy : {100 * correct / total}%')

Accuracy : 100.0%
